[package]
name = "infinity-rs"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "Safe, idiomatic Rust bindings for the MSFS 2024 WASM SDK."
license = "MIT"
repository = "https://github.com/infinity-MSFS/infinity-rs"
homepage = "https://infinity-simulations.com/docs/developer/getting-started"
documentation = "https://infinity-simulations.com/docs/developer/getting-started"
readme = "../README.md"
authors = ["cameron_griego@protonmail.com"]
keywords = ["msfs", "flight-simulator", "wasm", "simconnect", "bindings"]
categories = ["api-bindings", "external-ffi-bindings", "simulation"]

[features]
default = ["wasm", "derive"]
wasm = []
simconnect = []
derive = ["dep:infinity_rs_derive"]

[dependencies]
infinity_rs_derive = { path = "../infinity_rs_derive", version = "0.1.0", optional = true }
bitflags = "1.3"
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
bindgen = "0.72"
infinity_rs_sdk = { path = "../infinity_rs_sdk", version = "0.1.0" }
cc = "1.0"

[[example]]
name = "simconnect_native"
required-features = ["simconnect"]

[[example]]
name = "simconnect_gauge"
required-features = ["simconnect"]
crate-type = ["cdylib"]

[[example]]
name = "charts_gauge"
crate-type = ["cdylib"]

[[example]]
name = "comm_bus_gauge"
crate-type = ["cdylib"]

[[example]]
name = "comm_bus_system"
crate-type = ["cdylib"]

[[example]]
name = "event_api"
crate-type = ["cdylib"]

[[example]]
name = "flow_system"
crate-type = ["cdylib"]

[[example]]
name = "io_system_simple"
crate-type = ["cdylib"]

[[example]]
name = "io_system"
crate-type = ["cdylib"]

[[example]]
name = "map_view_weather_radar"
crate-type = ["cdylib"]

[[example]]
name = "network_fetch_system"
crate-type = ["cdylib"]

[[example]]
name = "network_post_system"
crate-type = ["cdylib"]

[[example]]
name = "nvg_render"
crate-type = ["cdylib"]

[[example]]
name = "planned_route_system"
crate-type = ["cdylib"]

[[example]]
name = "vars_full_api"
crate-type = ["cdylib"]

[[example]]
name = "vfx_system"
crate-type = ["cdylib"]
