[package]
name = "infinity-msfs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
cargo_metadata = "0.18"
anyhow = "1"
thiserror = "1"
console = "0.15"
indicatif = "0.17"
msfs_sdk = { path = "../msfs_sdk" }
ureq = "2"
flate2 = "1"
tar = "0.4"
